spring:
  application:
    name: api-gateway
  zipkin: http://127.0.01:9411/
  sleuth:
    sampler:
      probability: 1
  cloud:
    gateway:
      routes:

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/auth/**


        - id: portalmanagement
          uri: lb://PORTAL-MANAGEMENT
          predicates:
            - Path=/api/v1/auth/**


      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:3000"
            allowed-methods: "GET, POST, PUT, DELETE, OPTIONS"
            allowed-headers: "Content-Type, Authorization, Accept, Origin, X-Requested-With, X-Csrf-Token, If-Match"
            allow-credentials: true
            max-age: 3600

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1
server:
  port: 9191