server:
  port: 8081

spring:
  application:
    name: userservice

  datasource:
    url: jdbc:postgresql://localhost:5433/auth_db?autoReconnect=true
    username: ${DATABASE_USERNAME:auth_user}
    password: ${DATABASE_PASSWORD:auth_pass}

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: public
